'use strict';


module.exports = {
	'language_in': 'ECMASCRIPT5',
	'compilation_level': 'ADVANCED_OPTIMIZATIONS',
	'checks-only': false,
	'charset': 'UTF-8',
	'jscomp_error': [
		// 'accessControls',
		// 'ambiguousFunctionDecl',
		// 'checkEventfulObjectDisposal',
		// 'checkRegExp',
		// 'checkStruct',
		// 'DictInheritance',
		// 'checkTypes',
		'checkVars',
		// 'conformanceViolations',
		// 'const',
		// 'constantProperty',
		// 'deprecated',
		// 'deprecatedAnnotations',
		// 'duplicateMessage',
		// 'es3',
		'es5Strict',
		// 'externsValidation',
		// 'fileoverviewTags',
		// 'globalThis',
		// 'inferredConstCheck',
		// 'internetExplorerChecks',
		// 'invalidCasts',
		// 'misplacedTypeAnnotation',
		// 'missingGetCssName',
		// 'missingProperties',
		// 'missingProvide',
		// 'missingRequire',
		// 'missingReturn',
		// 'newCheckTypes',
		// 'nonStandardJsDocs',
		// 'reportUnknownTypes',
		// 'suspiciousCode',
		// 'strictModuleDepCheck',
		// 'typeInvalidation',
		// 'undefinedNames',
		// 'undefinedVars',
		// 'unknownDefines',
		// 'uselessCode',
		// 'useOfGoogBase',
		// 'visibility'
	]
};
